# installation:
# sudo docker-compose run --entrypoint '/usr/bin/entrypoint /bin/bash' ynab
# winetricks allfonts (failed early due to missing xz in container, but seems to have helped with font issue)
# wine ~/ynab-setup.exe
version: '3.7'
services:
    ynab:
        build: .
        environment:
            - DISPLAY=xvncserver:0
            - WINEARCH=win32
        volumes:
            - ynab-appinst:/home/wineuser
            - ynab-data:/home/wineuser/Budget
            - ynab-xauthority:/Xauthority
            - ./YNAB 4_4.3.857_Setup.exe:/home/wineuser/ynab-setup.exe
            - ./lic.txt:/home/wineuser/ynab-lic.txt
        entrypoint:
            - bash
            - -c
            - sleep 5; /usr/bin/entrypoint wine "C:\\Program Files\\YNAB 4\\YNAB 4.exe"
        networks:
            - ynab-xvncserver
        # XXX why does it even require IPC for a remote X server?!! well, I can give it...
        ipc: container:docker-ynab_xvncserver_1
        stdin_open: true
        tty: true
        depends_on:
            - xvncserver
    xvncserver:
        image: suchja/x11server@sha256:0737c737e6e1a79bfe0fad30b58bc2c9a5f8d637b2f61603c89ca8d87a2a7a06
        environment:
            - VNC_PASSWORD
        volumes:
            - ynab-xauthority:/Xauthority
        networks:
            - ynab-xvncserver
        ports:
            - 5900:5900
        ipc: shareable
volumes:
    ynab-appinst:
    ynab-data:
    ynab-xauthority:
networks:
    ynab-xvncserver:
