# installation:
# sudo docker-compose run --entrypoint '/usr/bin/entrypoint /bin/bash' ynab
# winetricks allfonts (failed early due to missing xz in container, but seems to have helped with font issue)
# wine ~/ynab-setup.exe
version: '3.7'
services:
    ynab:
        image: scottyhardy/docker-wine@sha256:ca0481f5c953cbb9c40ce6e91c01f9bf06ea7de73094663f13931778f1060a58
        environment:
            - DISPLAY=novnc:0
            - WINEARCH=win32
        volumes:
            - ynab-appinst:/home/wineuser
            - ynab-data:/home/wineuser/Budget
            - ./YNAB 4_4.3.857_Setup.exe:/home/wineuser/ynab-setup.exe
            - ./lic.txt:/home/wineuser/ynab-lic.txt
        # XXX sleep is a hack to wait for server to be ready
        entrypoint:
            - bash
            - -c
            - sleep 5; /usr/bin/entrypoint wine "C:\\Program Files\\YNAB 4\\YNAB 4.exe"
        networks:
            - x11
        # XXX why does it even require IPC for a remote X server?!! well, I can give it...
        ipc: container:docker-ynab_novnc_1
        stdin_open: true
        tty: true
        depends_on:
            - novnc
    novnc:
        image: theasp/novnc@sha256:7d57a01c49c27e0ac643afdb4cce80eaca7e63282fa7b13568a7388e30635575
        networks:
            - x11
        ports:
            - 8080:8080
        ipc: shareable
volumes:
    ynab-appinst:
    ynab-data:
networks:
    x11:
