version: '3.7'
services:
    ynab:
        image: sha256:a0a599e5108e58806e8cf35b09bf1938c1c3f36585eb585d509874ef3eeef67d
        # ^^^ take https://gist.github.com/scintill/199c47a32a48cf52c9e415624715ccbc , run ynab installer (set XAUTHORITY=/home/wineuser/.Xauthority), set up license key, commit image
        environment:
            - DISPLAY=novnc:0
        volumes:
            - ynab-data:/home/wineuser2/Budget
        # XXX sleep is a hack to wait for server to be ready
        entrypoint:
            - bash
            - -c
            - sleep 3; /usr/bin/entrypoint wine "C:\\Program Files\\YNAB 4\\YNAB 4.exe"
        networks:
            - x11
        # XXX why does it even require IPC for a remote X server?!! well, I can give it...
        ipc: container:docker-ynab_novnc_1
        stdin_open: true
        tty: true
        depends_on:
            - novnc
    novnc:
        image: theasp/novnc@sha256:7d57a01c49c27e0ac643afdb4cce80eaca7e63282fa7b13568a7388e30635575
        networks:
            - x11
        ports:
            - 8080:8080
        ipc: shareable
        environment:
            - RUN_XTERM=no
volumes:
    ynab-data:
networks:
    x11:
